version: '3.9'
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
    restart: always
    tty: true
    stdin_open: true

  minio:
    image: quay.io/minio/minio
    container_name: minio
    command: 'server /data --console-address ":9001"'
    ports:
      - '9001:9001'
      - '9000:9000'
    restart: always

  mysql:
    image: 'mysql'
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_PASSWORD=pwd
      - MYSQL_USER=admin
      - MYSQL_DATABASE=mk
      - MYSQL_ROOT_PASSWORD=pwd
    restart: always
    tty: true
    stdin_open: true
